import type { Metadata } from "next";
import { Geist_Mono, Poppins, Playfair_Display, Lexend } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SmoothScrolling } from "@/components/SmoothScrolling";
import { FloatingNav } from "@/components/FloatingNav";
import { FloatingContact } from "@/components/FloatingContact";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-accent",
  style: ["normal", "italic"],
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={cn("h-full", "antialiased", poppins.variable, playfair.variable, lexend.variable, geistMono.variable)}
    >
      <body className="min-h-full flex flex-col font-sans">
        <SmoothScrolling>
          {children}
          <FloatingNav />
          <FloatingContact />
        </SmoothScrolling>
      </body>
    </html>
  );
}
